### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by shubhamverma27** [maheshmurthy/ethereum_voting_dapp#10]
Getting this error on deplying the chapter 3 application using truffle 3 ..
Please help!!

**Comment by shubhamverma27** [comment]
contractInstance.allCandidates.call().then(function(candidateArray) {

at this line!!

**Comment by maheshmurthy** [comment]
Old issue, please reopen if it is still happening
