### ISSUE TITLE
Error: The contract code couldn't be stored, please check your gas amount.

### ISSUE THREAD

**Issue by cassianobrexbit** [maheshmurthy/ethereum_voting_dapp#11]
Hello. I was trying to deploy the contract of the **chapter3** and the console printed this error:

> The contract code couldn't be stored, please check your gas amount.

I compared the file **2_deploy_contracts.js** used in **chapter3** with used in **chapter2** and I noticed that was missing the gas value as shown below:

```
// the actual chapter3 2_deploy_contracts.js file
var Voting = artifacts.require("./Voting.sol");
module.exports = function(deployer) {
  deployer.deploy(Voting, 1000, web3.toWei('0.1', 'ether'), ['Rama', 'Nick', 'Jose']);
}; 
```

```
//what I did
var Voting = artifacts.require("./Voting.sol");
module.exports = function(deployer) {
  deployer.deploy(Voting, 1000, web3.toWei('0.1', 'ether'), ['Rama', 'Nick', 'Jose'],{gas: 6700000});
};
```

It worked fine when I did it.
I don't know if it is correct or if I did something wrong.

Thanks!

**Comment by maheshmurthy** [comment]
Thank you! Your solution is correct. The default gas value has probably changed, I will update the code to specify gas
