### ISSUE TITLE
unable to complile the code

### ISSUE THREAD

**Issue by AbhishekPatnaik** [maheshmurthy/ethereum_voting_dapp#16]
Getting the following output on complining the code with :- 
     `compiledCode = solc.compile(code)`

Output:- 
`'{"errors":[{"component":"general","formattedMessage":"* Line 1, Column 1\\n  Syntax error: value, object or array expected.\\n* Line 1, Column 2\\n  Extra non-whitespace after JSON value.\\n","message":"* Line 1, Column 1\\n  Syntax error: value, object or array expected.\\n* Line 1, Column 2\\n  Extra non-whitespace after JSON value.\\n","severity":"error","type":"JSONError"}]}'`

**Comment by Juneyoung-Kang** [comment]
I resolved this issue by using this repository contents, not blog instruction.
Try to use this repository's npm packages and index.js. (It seems different from the blog.) 😄

**Comment by Juneyoung-Kang** [comment]
I think It is a matter of version conflicts between `package.json` and `Voting.sol`. Please check my pull request #17 and run that command again. 😄

**Comment by AbhishekPatnaik** [comment]
hey, @Juneyoung-Kang i tried out the same but it didn't work for me. Please help me out with it.

**Comment by Juneyoung-Kang** [comment]
I suggest you clone my forked [repository](https://github.com/Juneyoung-Kang/ethereum_voting_dapp) and run following instructions.

```bash
git clone https://github.com/Juneyoung-Kang/ethereum_voting_dapp
cd ethereum_voting_dapp
cd chapter1
npm install
npm start

/* Open another terminal window and make sure both are running. */
node
> Web3 = require('web3')
> web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
> web3.eth.accounts
> code = fs.readFileSync('Voting.sol').toString()
> solc = require('solc')
> compiledCode = solc.compile(code)
```

**Comment by maheshmurthy** [comment]
@AbhishekPatnaik You have a syntax error in your code. Copy paste your code to remix.ethereum.org so you can easily track down the issue.

**Comment by AbhishekPatnaik** [comment]
Hey, @maheshmurthy @Juneyoung-Kang thanks for your help it was because of the version conflicts as suggested by @Juneyoung-Kang. Thanks.

**Comment by ghost** [comment]
> Hey, @AbhishekPatnaik could you please tell what exactly you did to overcome this issue even i'm getting the same error as well.

**Comment by AbhishekPatnaik** [comment]
@Rakhi31 i found out the solution following this pull request https://github.com/maheshmurthy/ethereum_voting_dapp/pull/17

**Comment by Eddie2111** [comment]
Let's just assume you have a `contract.sol` file inside your src dir. The module which will read the smart contract must have a structure like this.
```

const path = require('path');
const fs = require('fs');
const solc = require('solc');

const contractPath = path.resolve(__dirname, 'contract.sol');
const contractSource = fs.readFileSync(contractPath, 'utf8');

const input = {
    language: 'Solidity',
    sources: {
        'contract.sol': {
            content: contractSource
        }
    },
    settings: {
        outputSelection: {
            '*': {
                '*': ['*']
            }
        }
    }
};
const contractSources = fs.readFileSync('contract.sol', 'utf8').toString();
const output = JSON.parse(solc.compile(JSON.stringify(input)));
```

Assuming the `contract.sol` as,
```

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

contract MyContract {
    uint256 myNumber;

    function setNumber(uint256 _number) public {
        myNumber = _number;
    }

    function getNumber() public view returns (uint256) {
        return myNumber;
    }
}

```

now it will work, you must check that the version number of your solidity code and the version number of solidity compiler must match. Or you may change the version number on your code according to your solidity compiler version which is located in your `package.json`
