### ISSUE TITLE
Why not use address.transfer?

### ISSUE THREAD

**Issue by wilfreddenton** [maheshmurthy/ethereum_voting_dapp#3]
```
function transferTo(address account) {
    if (!account.call.value(this.balance)()) throw;
}
```

This function appears on line 125 in `Voting.sol` in chapter 3. I'm wondering why the function isn't simply: `account.transfer(this.balance);`?

**Comment by wilfreddenton** [comment]
I know why now. Because `address.transfer` is only available in solc 4.10 and truffle is still using 4.8.

**Comment by maheshmurthy** [comment]
Thanks, I didn't know about that method when I wrote the code. I will update it when truffle starts supporting it.

**Comment by pgrzesik** [comment]
Hey, about that issue, Truffle from version 3.2.2 is using solc 4.11

**Comment by maheshmurthy** [comment]
Updated the code!

**Comment by cjchalmers** [comment]
Hi Mahesh - great tutorials, thx!
I am just completing number three and whilst compiling the code I get an error in the transferTo function that the "Member balance not found or visible". I don't see it defined anywhere in the contract, am I missing something?
