### ISSUE TITLE
Update pragma

### ISSUE THREAD

**Issue by mcgoddard** [maheshmurthy/ethereum_voting_dapp#6]
`pragma solidity ^0.4.6; //We have to specify what version of the compiler this code will use`
Line 1 of Voting.sol should probably read:
`pragma solidity ^0.4.10; //We have to specify what version of the compiler this code will use`
Given the change to:
`account.transfer(this.balance);`
on line 126 the contract will no longer compile on solc version <0.4.10.
This gives the error:
> Compiling ./contracts/Voting.sol...
> 
> /home/vagrant/ethereum_voting_dapp/chapter3/contracts/Voting.sol:126:5: Error: Member "transfer" not found or not visible after argument-dependent lookup in address
>     account.transfer(this.balance);
>     ^--------------^
> Compiliation failed. See above.

On previous solc versions.
I'd do a pull request but I'm having trouble installing the latest Truffle at the moment so can't verify the fix.

**Comment by maheshmurthy** [comment]
Thanks for pointing it out! It's updated now.
