### ISSUE TITLE
throw is deprecated

### ISSUE THREAD

**Issue by SmokinCaterpillar** [maheshmurthy/ethereum_voting_dapp#7]
Hi, first of all thanks for the great tutorial.

I just came across one minor issue. `throw` in `Voting.sol` is [deprecated](https://www.reddit.com/r/ethereum/comments/6llgxv/solidity_0413_released/).

Does it make sense to replace it with `revert()`?

**Comment by maheshmurthy** [comment]
Definitely. You can send a pull request or I will update it in next day or so. Thanks for pointing it out.

**Comment by SmokinCaterpillar** [comment]
Made a pull request.

**Comment by maheshmurthy** [comment]
Thanks!
