### ISSUE TITLE
when i try to buy token for voting there isn't any token solded

### ISSUE THREAD

**Issue by kenken64** [maheshmurthy/ethereum_voting_dapp#9]
it seems like it keep returning zero 

var buyObject = {
    value: 25,
    from: web3.eth.accounts[0]
};
contractInstance.buy.call(buyObject).then(function(result) {
    console.log(">>>> " + result);
    web3.eth.getBalance(contractInstance.address, function(error, result) {
        console.log(result);
        console.log(web3.fromWei(result.toString()));
    });
}).catch(function(err) {
    console.log("Error creating contract!" + err);
    console.log(err.stack);
});

Account 0 : 99.99999999999662
Account 1 : 100
Account 2 : 99.99999999999846

**Comment by maheshmurthy** [comment]
It looks like the code you have is very different from what is in this repository. Please open an issue if the code in this repo has an issues. Feel free to put your code in a repo and message me, I will try to help.
